# Generated by Django 4.2.7 on 2024-01-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsignaturaEFGT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreAsignaturaEFGT', models.CharField(max_length=150)),
                ('creditosAsignaturaEFGT', models.PositiveIntegerField()),
                ('fechaInicioAsignaturaEFGT', models.DateField()),
                ('fechaFinalizacionAsignaturaEFGT', models.DateField()),
                ('profesorAsignaturaEFGT', models.CharField(max_length=150)),
                ('silaboAsignaturaEFGT', models.CharField(max_length=150)),
                ('tipoAsignaturaEFGT', models.CharField(max_length=150)),
                ('requisitosAsignaturaEFGT', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='CarreraEFGT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCarreraEFGT', models.CharField(max_length=100)),
                ('directorCarreraEFGT', models.CharField(max_length=100)),
                ('logoCarreraEFGT', models.FileField(blank=True, null=True, upload_to='logos')),
                ('duracionCarreraEFGT', models.CharField(max_length=10)),
                ('facultadCarreraEFGT', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CursoEFGT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nivelCursoEFGT', models.CharField(max_length=50)),
                ('descripcionCursoEFGT', models.TextField()),
                ('aulaCursoEFGT', models.PositiveIntegerField()),
                ('horario_curso_efgt', models.CharField(help_text='Formato HH:MM - HH:MM', max_length=20)),
                ('periodoCursoEFGT', models.CharField(max_length=150)),
            ],
        ),
    ]
