# Generated by Django 4.2.7 on 2024-01-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatriculasEFGT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursoefgt',
            old_name='horario_curso_efgt',
            new_name='horarioCursoEFGT',
        ),
        migrations.AlterField(
            model_name='carreraefgt',
            name='duracionCarreraEFGT',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carreraefgt',
            name='facultadCarreraEFGT',
            field=models.CharField(max_length=100),
        ),
    ]
