# Generated by Django 4.2.7 on 2024-01-29 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MatriculasEFGT', '0002_rename_horario_curso_efgt_cursoefgt_horariocursoefgt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaturaefgt',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MatriculasEFGT.cursoefgt'),
        ),
        migrations.AddField(
            model_name='cursoefgt',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='MatriculasEFGT.carreraefgt'),
        ),
    ]
